name: Testing and Coverage

on:
  pull_request:
    branches: [ main, integration ]
    paths-ignore:
        - '**.md'
        - '**.rst'
  push:
    branches:
      - main
    paths-ignore:
        - '**.md'
        - '**.rst'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.9, '3.10', '3.11']

        steps:
          - uses: actions/checkout@v2
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
                apt install -y gcc
                python3 -m pip install --upgrade pip
                python3 -m pip install -r requirements.txt
                python3 -m pip install pytest
                python setup.py build_ext --inplace
          - name: Test with pytest
            run: |
              pytest -s
          - if: ${{ matrix.python-version == '3.10' }}
            name: Extract coverage
            run: |
                # Run coverage save the results
                python3 -m pytest --cov=pointsnobal --cov-fail-under=80
                SUMMARY=`coverage report -m | grep TOTAL`
                # Save results as ENV var
                COVERAGE=$(python -c "print('$SUMMARY'.split(' ')[-1])")
                echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
                # var REF = 'refs/pull/27/merge.json';
                REF=${{ github.ref }}
                # console.log('github.ref: ' + REF);
                echo "github.ref: $REF"
                # var PATHS = REF.split('/');
                IFS='/' read -ra PATHS <<< "$REF"
                # var BRANCH_NAME = PATHS[1] + PATHS[2];
                BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
                # console.log(BRANCH_NAME); // 'pull_27'
                echo $BRANCH_NAME
                # process.env.BRANCH = 'pull_27';
                echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
          - if: ${{ matrix.python-version == '3.10' }}
            name: Create the Badge
            uses: schneegans/dynamic-badges-action@v1.0.0
            with:
                auth: ${{ secrets.GIST_SECRET }}
                gistID: 04da387b53bdb4a3aa31253789550a9f
                filename: pointsnobal__${{ env.BRANCH }}.json
                label: Coverage
                message: ${{ env.COVERAGE }}
                color: green
